# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('james', '0002_auto_20180428_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='persons',
            new_name='person',
        ),
    ]
